### ISSUE TITLE
Replace Mtcnn with other detector

### ISSUE THREAD

**Issue by soham24** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#10]
Can I replace mtcnn with another detector?

**Comment by HansRen1024** [comment]
@soham24 Sure. The job of RNet is to offer you an initial bbox effectively and correctly. You can replace it whatever you prefer.

**Comment by soham24** [comment]
@HandsomeHans Thank you. I am trying to implement it with tflite in mobile.
I only run one model for detection. it gives me probability and rect of the face.
