### ISSUE TITLE
tld尺度几乎没有变化？

### ISSUE THREAD

**Issue by NiYien** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#14]
调试的时候发现，在tld跟踪的时候，尺度几乎是都是1，没有变化， 请问这是tld哪里出问题了吗？

**Comment by HansRen1024** [comment]
@HiDream 我在代码中把人脸框固定了，每次跑RNet检测一次人脸，才会更新人脸框的尺寸。
