### ISSUE TITLE
你好，请问该追踪实现是否有gpu版本？

### ISSUE THREAD

**Issue by HeshanMountteen** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#16]
我发现该追踪由于是在cpu上实现的，对CPU的占用还是挺高的，请问是否有gpu版本的？

**Comment by HansRen1024** [comment]
@HeshanMountteen 我实现的时候ncnn还没有添加gpu支持，现在应该有gpu支持了，你可以关注一下ncnn社区。

**Comment by HeshanMountteen** [comment]
> @HeshanMountteen 我实现的时候ncnn还没有添加gpu支持，现在应该有gpu支持了，你可以关注一下ncnn社区。

好的，感谢回复

**Comment by HeshanMountteen** [comment]
> 我发现该追踪由于是在cpu上实现的，对CPU的占用还是挺高的，请问是否有gpu版本的？

个人对人脸追踪有点一知半解，如果人脸特征点定位（比如68个特征点）稳定性不好，存在抖动现象，我在某些博客和论文中看到说可以借助人脸追踪来提升，想问下是为什么？原理是啥？您知道吗
