### ISSUE TITLE
请问人脸在移动的时候，人脸框滞后很大是怎么回事

### ISSUE THREAD

**Issue by ZardZen** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#19]

**Comment by HansRen1024** [comment]
我记得有个计算平均帧的参数, 改小一点,应该就不会有滞后的情况了. 我记不太清楚了.你试试改改这个 ./include/mtcnn.h 第68行, const int MIN_DET_SIZE = 10;
