### ISSUE TITLE
make ：缺少“net.h”

### ISSUE THREAD

**Issue by wyuzyf** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#2]
您好，请问下这个文件在哪里？谢谢

**Comment by zyWang-Power** [comment]
您好，这个文件你找到了吗？

**Comment by HansRen1024** [comment]
net.h是ncnn项目的头文件。

**Comment by HansRen1024** [comment]
@wyuzyf @yuanbao888

**Comment by zyWang-Power** [comment]
首先，感谢您的回复，我研一，刚入门，最近研究kcf, 运用到工程里面人脸跟踪，对这个ncnn不太了解，今天看到公众号上面介绍您的做法，想比较一下kcf和您做法的快慢，您能否告知我 这个头文件哪里有？网上我找了半天没找到！


------------------ 原始邮件 ------------------
发件人: "Hans Ren"<notifications@github.com>;
发送时间: 2019年1月12日(星期六) 晚上9:49
收件人: "HansRen1024/Face-Tracking-Based-on-OpenTLD-and-RNet"<Face-Tracking-Based-on-OpenTLD-and-RNet@noreply.github.com>;
抄送: "元宝"<979506441@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [HansRen1024/Face-Tracking-Based-on-OpenTLD-and-RNet] make ：缺少“net.h” (#2)




net.h是ncnn项目的头文件。

**Comment by zyWang-Power** [comment]
已解决  谢谢您！ 


------------------ 原始邮件 ------------------
发件人: "Hans Ren"<notifications@github.com>;
发送时间: 2019年1月12日(星期六) 晚上9:49
收件人: "HansRen1024/Face-Tracking-Based-on-OpenTLD-and-RNet"<Face-Tracking-Based-on-OpenTLD-and-RNet@noreply.github.com>;
抄送: "元宝"<979506441@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [HansRen1024/Face-Tracking-Based-on-OpenTLD-and-RNet] make ：缺少“net.h” (#2)




net.h是ncnn项目的头文件。

**Comment by wyuzyf** [comment]
谢谢，已经复制过去

**Comment by wyuzyf** [comment]
谢谢，明白
