### ISSUE TITLE
Needs a sqrt before the norm?

### ISSUE THREAD

**Issue by hyx07** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#20]
https://github.com/HansRen1024/Face-Tracking-Using-CNN-and-Optical-Flow/blob/1bb71d9b133f560916334ec3859f917abcbd38d0/include/TLD.cpp#L61

Hi, to calculate the ratio between new length and old length, I think it needs a sqrt before the norm? As the norm calculates the sum of square value only. This issue exists also in the python version, thank you!

**Comment by HansRen1024** [comment]
@hyx07 Thank you for pointing this out. A sqrt would make the ratio curve be smoother and more stable, which is helpful to stabilise the bounding box. You are more than welcome to make a pull request.

**Comment by hyx07** [comment]
pull request submitted for both versions, thank you for your work!

**Comment by HansRen1024** [comment]
@hyx07  PRs are approved. Thank you.
