### ISSUE TITLE
gcc版本是多少？

### ISSUE THREAD

**Issue by wyuzyf** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#3]
您好，请问下您make时gcc的版本号是多少？
我的是4.8.2，make时报错：
“/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: 错误：将类型为‘Bbox&’的引用初始化为类型为‘const Bbox’的表达式无效”
这应该是gcc的bug吧，查到说4.9.0+就不会出现这个问题了。
谢谢～

**Comment by HansRen1024** [comment]
@wyuzyf g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by HansRen1024** [comment]
@wyuzyf  如果不方便改环境，可以考虑将Bbox改成cv::Rect

**Comment by wyuzyf** [comment]
ok，我先升级下gcc，看能行不，谢谢～

**Comment by lrain-CN** [comment]
> 
> 
> 您好，请问下您make时gcc的版本号是多少？
> 我的是4.8.2，make时报错：
> “/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: 错误：将类型为‘Bbox&’的引用初始化为类型为‘const Bbox’的表达式无效”
> 这应该是gcc的bug吧，查到说4.9.0+就不会出现这个问题了。
> 谢谢～

已解决，sort 排序那边的错 排序函数参数需要加const， bool sortScore(const Bbox& lsh, const Bbox& rsh)
