### ISSUE TITLE
关于保存视频的问题

### ISSUE THREAD

**Issue by zonegoalshall** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#4]
我uncomment了视频存储相关的语句，但是运行后目录内没有保存的文件，是哪里还需要调整嘛？

**Comment by HansRen1024** [comment]
@zonegoalshall 木有啦，保存视频就那五句代码。。

**Comment by zonegoalshall** [comment]
可是为什么没有视频保存下来呀（笑哭脸）

**Comment by HansRen1024** [comment]
@zonegoalshall 再仔细查看一下吧 -0-  能不能是CV_FOURCC('M', 'P', '4', '2')解码问题？换其他的试试。
