### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by northeast250** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#5]
MacOSX 不支持吗？ncnn这个库明确说明了，xcode do not support openmp feature，我就是在mac上用xcode编译的ncnn，然后在Face-Tracking-Based-on-OpenTLD-and-RNet/build编译的时候，就遇到了这个问题。

clang: error: unsupported option '-fopenmp'

Build for MacOSX
install xcode and protobuf

Because the compiler bundled with xcode do not support openmp feature, you cannot enable the multithreading inference feature of ncnn library, if you build with xcode.

$ homebrew install protobuf
$ cd <ncnn-root-dir>
$ mkdir -p build
$ cd build
$ cmake ..
$ make -j4
$ make install
pick build/install folder for further usage

Ali:build admin$ make
Scanning dependencies of target TLD
[ 16%] Building CXX object CMakeFiles/TLD.dir/include/TLD.o
clang: error: unsupported option '-fopenmp'
make[2]: *** [CMakeFiles/TLD.dir/include/TLD.o] Error 1
make[1]: *** [CMakeFiles/TLD.dir/all] Error 2
make: *** [all] Error 2

**Comment by HansRen1024** [comment]
@northeast250 我这里openmp也只是ncnn需要，你在mac系统下如果ncnn不支持openmp，直接去掉这个选项试试。

**Comment by northeast250** [comment]
怎么去掉ncnn呢？
include_directories (
	${PROJECT_SOURCE_DIR}/./include
	${OpenCV_INCLUDE_DIRS}
	#/Users/admin/ncnn/build/install/include
	)
ADD_DEFINITIONS(
	-O3 -fPIC -fopenmp -std=c++11
	)
#compile tld libraries
add_library(TLD ${PROJECT_SOURCE_DIR}/ ./include/TLD.cpp)
#compile shared library
add_library(ncnn_mtcnn_tld_so SHARED ./include/ncnn_mtcnn_tld_so.cpp)
#FIND_LIBRARY(NCNN_LIB ncnn /Users/admin/ncnn/build/install/lib NO_DEFAULT_PATH)

我把ncnn注释掉了，还是报错


Ali:build admin$ make
Scanning dependencies of target TLD
[ 16%] Building CXX object CMakeFiles/TLD.dir/include/TLD.o
clang: error: unsupported option '-fopenmp'
make[2]: *** [CMakeFiles/TLD.dir/include/TLD.o] Error 1
make[1]: *** [CMakeFiles/TLD.dir/all] Error 2
make: *** [all] Error 2

**Comment by HansRen1024** [comment]
@northeast250 ncnn是人脸检测的推理框架，可以替换用caffe来做，不过tld后面rnet那块也要改成caffe。我之前的意思是你把-fopenmp选项删掉试试，nann还是要保留的，否则你代码改动较大。
