### ISSUE TITLE
mtcnn.rnet(img, pbox) is nan

### ISSUE THREAD

**Issue by dajidali010** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#6]
Thanks for your job! But when I test your code with a local movie, after function "tld.processFrame(last_gray,current_gray,pbox,status);" in ncnn_mtcnn_tld_so.cpp ,sometimes the x, width,height of pbox will be negative, and "mtcnn.rnet(img, pbox)" will be nan or -nan.

**Comment by HansRen1024** [comment]
@dajidali010 Hi, it is clear that a wrong pbox must lead to a wrong result of rnet. However, I have no idea how a wrong pbox produces. I have never meet this issue before. Maybe you should check the inputs, "last_gray" and "current_gray", or "box" in tld.defineLastBox(box);.
