### ISSUE TITLE
if remove the classifiers in the algorithm,the learning module in the original algorithm is gone, then use the tld is not much sense？

### ISSUE THREAD

**Issue by GaoLihui** [HandsomeHans/Face-Tracking-Based-on-OpenTLD-and-RNet#8]
Thanks for sharing your work with us.I have a few questions .
If removing the classifiers in the algorithm,the learning module in the original algorithm is gone, then use the tld is not much sense？I think the biggest contribution of TLD is the framework of tracking-learning-detection.
Whether the effect will be better,if i use another tracker,faster than tld？

**Comment by HansRen1024** [comment]
@GaoLihui Actually, the methods I used from TLD are feature points extracting and optical flow which are the reason why this algorithm runs so fast and has a stable box. Some other guys also asked me why not using other tracking methods such as KCF which has better performance than TLD. At that time, TLD had faced the requirement and I did not have enough time to do more research on it.
